---
resources:
- name: source
  type: git
  source:
      uri: git@github.com:evcraddock/goarticles.git
      branch: master
      private_key: ((github.private-key))

- name: version
  type: semver
  source:
      driver: git
      uri: git@github.com:evcraddock/goarticles.git
      branch: version
      file: version
      private_key: ((github.private-key))

- name: docker-file
  source:
      repository: gcr.io/erikvancraddock/goarticles
      username: ((gcr.username))
      password: ((gcr.password))
  type: docker-image

jobs:
- name: tests
  public: true
  plan:
  - get: source
    trigger: false
  - task: run-tests
    file: source/ci/run-tests.yml

- name: build
  public: true
  plan:
  - get: source
    trigger: true
    passed: [tests]
  - get: version
    params: {bump: patch}
  - task: build
    file: source/ci/build.yml
  - put: docker-file
    params:
        build: built/
        tag: version/version
        tag_as_latest: true
  - put: version
    params: {file: version/version}

- name: deploy-gcloud
  plan:
  - get: source
    trigger: true
    passed: [build]
  - get: docker-file
    trigger: true
    passed: [build]
  - get: version
    trigger: true
    passed: [build]
  - task: deploy
    file: source/ci/deploy.yml
