---
resources:
- name: source
  type: git
  source:
      uri: git@github.com:evcraddock/goarticles.git
      branch: master
      private_key: ((github.private-key))

- name: version
  type: semver
  source:
      driver: git
      uri: git@github.com:evcraddock/goarticles.git
      branch: version
      file: version
      private_key: ((github.private-key))

- name: docker-file
  source:
      repository: gcr.io/erikvancraddock/goarticles
      username: ((gcr.username))
      password: ((gcr.password))
  type: docker-image

jobs:
- name: deploy-gcloud
  plan:
  - get: source
    trigger: false
  - get: docker-file
    trigger: false
  - get: version
    trigger: false
  - task: deploy
    file: source/ci/deploy.yml